[{"error":"There was an error sending data to the pipeline: Received none result for Model Inference","error_type":"InternalError"}]